### PR TITLE
Feature 3

### PR DESCRIPTION
**Pull request by shadrxcc**
This feature contains the remaining sections of the original page. The in magazine and editor’s pick section, the Us section and the subscribe and newsletter section inclusive. Bootstrap grid system is used for these sections layout.

### CODE REVIEW

**Review by soieducation — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🚦 

### Hello @Ademola101 @YinkTech  and @shadrxcc  :wave: 

### You have done an amazing job on this milestone, your sections are looking almost the same as the original. :clap: However, there are still changes to be made.

# [Required Changes] :warning: 
### Mobile view
- [x] In the magazine section the articles have no spacing in between them. (Same for editors pick section)
- [ ] The text in subscribe and newsletter section should be centred.
- [ ] The email input and free sign up button should be aligned side by side(for all views)

### Tablet view
- [x] Editors pick section should have only two columns.

### Desktop view
- [ ] The newsletter section is not aligned with subscribe section as on the original page.
- [ ] The buttons should have a red colour in subscribe and newsletter section.

# [Optional Changes]  
- [ ] There's a lot of blank space before the 'In the magazine' section for desktop view, kindly check that.
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Review by soieducation — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🚦 

### Hello @Ademola101 @YinkTech  and @shadrxcc  :wave: 

### Good job on making the changes required from the last review, however there are still some changes left.

# [Required Changes] :warning: 
### Mobile view
- [ ] In the magazine section the articles have no spacing in between them. (Same for editors pick section)
- [ ] The free sign up button extends outside the border

### Tablet view
- [ ] The editors pick section is covering some parts of the 'In the magazine' section.
Screenshot (210)

___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Review by soieducation — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @Ademola101 @YinkTech  and @shadrxcc :wave: 

### You have done an amazing job on this milestone, congratulations! Your project is approved :clap: :clap: :clap: 

### Good luck with your next project :rocket: 

### Remember to submit your project completion form individually
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Comment by Ademola101** [comment]
@soieducation Thanks for the review

**Pull request merged**
